### ISSUE TITLE
thing.call_endpoint crashing on ESP8266

### ISSUE THREAD

**Issue by rafaalvfe** [thinger-io/Arduino-Library#12]
Hey! I'm trying the call_endpoint function with the arduino library in an esp8266-12e, when I run the function sometimes it works and I receive the info but all the time the esp restarts, like it's crashing. This is my code:

`
    thing.call_endpoint("puerta_abierta");`

and esp log: 

`ets Jan  8 2013,rst cause:4, boot mode:(1,6)
`

**Comment by alvarolb** [comment]
Hi, can you share your sketch (without credentials)? The rst cause seems to be a watchdog problem...
