### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Magic-Doufu** [thinger-io/Arduino-Library#27]
Arduino IDE return an compile error in thinger_resource.hpp when I include "ThingerYun.h".
enum access_type > "INTERNAL" is redefined.
This is defined in Arduino.hpp and is included by default.
I try to delete thinger_resource.hpp line 56.
It works.

**Comment by arslan437** [comment]
@Magic-Doufu is your issue fixed?

**Comment by Magic-Doufu** [comment]
@arslan437 
Yes.
It just need to delete/comment out line 56 in "thinger_resource.hpp" file.

**Comment by arslan437** [comment]
yes, it fixed the issue.
