### ISSUE TITLE
Compile error - MKRWifi1010

### ISSUE THREAD

**Issue by grezco** [thinger-io/Arduino-Library#30]
Hello,

With Arduino IDE 1.8.10, ArduinoMKR1010 example return an compile error in thinger :

….arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\c++\7.2.1\bits\stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2

     min(const _Tp& __a, const _Tp& __b, _Compare __comp)

Any idea ?

**Comment by Magic-Doufu** [comment]
insert
```
#undef max
#undef min
```
before
` #include <thingerWifi101.h> `

then it's work.

But I can't find the min/max macro in the thinger.io / Wifi101 library.

**Comment by grezco** [comment]
Thank you very much.
It's work
