### ISSUE TITLE
Bench of errors while compiling thinger code after updating to last version

### ISSUE THREAD

**Issue by rin67630** [thinger-io/Arduino-Library#34]
Please help.
Wanting to test the console feature, I have uploaded today the complete zipped Thinger Arduino Master library from Github to my current Arduino IDE.

Now the IDE is broken and my sketches -also the old ones- do not compile for an ESP8266 any more.

Her are the errors reported.

Compiling library “thinger.io”
“C:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506/bin/xtensa-lx106-elf-g++” -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3/tools/sdk/include” “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3/tools/sdk/lwip2/include” “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3/tools/sdk/libc/xtensa-lx106-elf/include” “-IC:\Users\MICHEL~1\AppData\Local\Temp\arduino_build_45804/core” -c -Os -g -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++11 -MMD -ffunction-sections -fdata-sections -fno-exceptions -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10813 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 “-DARDUINO_BOARD=“ESP8266_NODEMCU”” -DLED_BUILTIN=2 -DFLASHMODE_DIO -DESP8266 “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266” “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\variants\nodemcu” “-IC:\Users\RIN67630\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\Wire” “-ID:\5_Tinker\Arduino\libraries\INA2xx\src” “-ID:\5_Tinker\Arduino\libraries\ArduinoJson\src” “-ID:\5_Tinker\Arduino\libraries\TridentTD_OpenWeather-master\src” “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src” “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266HTTPClient\src” “-IC:\Users\Michel Firholz\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ArduinoOTA” “-ID:\5_Tinker\Arduino\libraries\thinger.io\src” “-ID:\5_Tinker\Arduino\libraries\Arduino-Library-master\src” “-IC:\Users\RIN67630\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\EEPROM” “-IC:\Users\RIN67630\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266mDNS\src” “D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.cpp” -o “C:\Users\RIN67630\AppData\Local\Temp\arduino_build_45804\libraries\thinger.io\thinger\ThingerConsole.cpp.o”
In file included from D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.h:6:0,
from D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.cpp:1:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:89:25: error: expected ‘)’ before ‘&’ token
ThingerClient(Client& client, const char* user, const char* device, const char* device_credential) :
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:432:5: error: ‘Client’ does not name a type
Client& get_client(){
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:438:5: error: ‘Client’ does not name a type
Client& client_;
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘virtual bool ThingerClient::read(char*, size_t)’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:118:24: error: ‘client_’ was not declared in this scope
int read = client_.readBytes((char*)buffer+total_read, size-total_read);
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘bool ThingerClient::client_write(const char*, size_t)’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:213:26: error: ‘client_’ was not declared in this scope
size_t written = client_.write((uint8_t*) buffer, size);
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘virtual void ThingerClient::disconnected()’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:256:9: error: ‘client_’ was not declared in this scope
client_.stop();
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘virtual bool ThingerClient::connect_socket()’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:270:16: error: ‘client_’ was not declared in this scope
return client_.connect(host_, secure_connection() ? THINGER_SSL_PORT : THINGER_PORT);
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘bool ThingerClient::handle_connection()’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:352:12: error: ‘client_’ was not declared in this scope
if(client_.connected()) return true;
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘bool ThingerClient::connect_client()’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:370:9: error: ‘client_’ was not declared in this scope
client_.stop(); // cleanup previous socket
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘void ThingerClient::stop()’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:395:9: error: ‘client_’ was not declared in this scope
client_.stop();
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘void ThingerClient::handle()’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:402:32: error: ‘client_’ was not declared in this scope
size_t available = client_.available();
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h: In member function ‘bool ThingerClient::is_connected() const’:
D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:415:16: error: ‘client_’ was not declared in this scope
return client_.connected();
^
D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.cpp: In constructor ‘ThingerConsole::ThingerConsole(ThingerClient&)’:
D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.cpp:9:15: error: no match for ‘operator>>’ (operand types are ‘thinger::thinger_resource’ and ‘ThingerConsole::ThingerConsole(ThingerClient&)::_lambda0’)
resource >> [&](pson& out){
^
D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.cpp:9:15: note: candidate is:
In file included from D:\5_Tinker\Arduino\libraries\thinger.io\src/thinger/thinger.h:29:0,
from D:\5_Tinker\Arduino\libraries\thinger.io\src/ThingerClient.h:28,
from D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.h:6,
from D:\5_Tinker\Arduino\libraries\thinger.io\src\thinger\ThingerConsole.cpp:1:
D:\5_Tinker\Arduino\libraries\thinger.io\src/thinger/thinger_resource.hpp:305:10: note: void thinger::thinger_resource::operator>>(void (*)(protoson::pson&))
void operator>>(void (out_function)(protoson::pson& out)){
^
D:\5_Tinker\Arduino\libraries\thinger.io\src/thinger/thinger_resource.hpp:305:10: note: no known conversion for argument 1 from ‘ThingerConsole::ThingerConsole(ThingerClient&)::__lambda0’ to 'void ()(protoson::pson&)’
Multiple libraries were found for “ArduinoOTA.h”
Used: C:\Users\RIN67630\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ArduinoOTA
Not used: D:\5_Tinker\Arduino\libraries\ArduinoOTA
Multiple libraries were found for “ThingerESP8266.h”
Used: D:\5_Tinker\Arduino\libraries\thinger.io
Not used: D:\5_Tinker\Arduino\libraries\Arduino-Library-master

**Comment by alvarolb** [comment]
Fixed on 2.17.0 library version!
