### ISSUE TITLE
Compiling issue on PIO / esp32

### ISSUE THREAD

**Issue by CommanderRedYT** [thinger-io/Arduino-Library#35]
This library always causes compiling issues and I don't know why...

![grafik](https://user-images.githubusercontent.com/43087936/110200445-67e4b700-7e5e-11eb-851b-81be522fcaf3.png)
It just feels like the whole library is broken...

**Comment by CommanderRedYT** [comment]
Update: Tried in Arduino IDE and got 1:1 the same issue...

**Comment by alvarolb** [comment]
Hi @CommanderRedYT. It should be fixed in the recently released 2.16.0 version. Let me know if it works for you!

**Comment by CommanderRedYT** [comment]
Compiling seems to work if I put the library folder in the lib/ folder (guessing Platformio isn't just up-to-date yet) 
thanks!

**Comment by alvarolb** [comment]
Yes, Platformio and Arduino takes some hours to update to latest version. Thanks for the feedback!
