### ISSUE TITLE
ESP32 Can't connect to Thinger.io 

### ISSUE THREAD

**Issue by mimamrafi** [thinger-io/Arduino-Library#38]
Hello sir, I'm sorry.
Previously, i have a tutorial about using thinger.io to control the esp32. But now, I follow my tutorial, the thinger.io in the website, my device still disconnect in state column. I use the example code of thinger.io/esp32 . The source is done uploading and the wifi has been connected to esp32, but thinger.io in the website still disconnect. Thank you for your support

**Comment by alvarolb** [comment]
Fixed on latest version 2.17.0!
