### ISSUE TITLE
OTA support in "WebConfig/WiFiManager"

### ISSUE THREAD

**Issue by georgevbsantiago** [thinger-io/Arduino-Library#39]
In general, devices sold by companies use "WebConfig/WiFiManager", as it is the user who will indicate the SSID and password of the WIFI router.

It would be important to update "ThingerWebConfig.h" to support OTA update and ESP32 support (if WiFiManager library already supports ESP32)

**Comment by alvarolb** [comment]
Fixed on #43 !
