### ISSUE TITLE
Typo in the example code, file: ArduinoENC28J60

### ISSUE THREAD

**Issue by Eteroxee** [thinger-io/Arduino-Library#5]
Typo in file: ArduinoENC28J60, line 9. No quotation marks. Looks like this:

`ThingerENC28J60 thing(USERNAME, DEVICE_ID, DEVICE_CREDENTIAL);`

instead of this:

`ThingerENC28J60 thing("USERNAME", "DEVICE_ID", "DEVICE_CREDENTIAL");`

It is in the documentation as well.

**Comment by alvarolb** [comment]
Hi! looking to the code, the example seems to be correct. Notice that the USERNAME, DEVICE_ID, and DEVICE_CREDENTIAL is defined in the previous lines, so the example should be able to compile.

Bests.
