### ISSUE TITLE
Thinger locks up ESP8266

### ISSUE THREAD

**Issue by dudesky71** [thinger-io/Arduino-Library#7]
I'm using the basic example 8266 sketch on a WeMos D1 Mini Pro. The module will randomly lock up hard. It seems to do it more when I'm logged into my thinger dashboard.

Any ideas of what could be causing this? I've also posted on the 8266.

Thank you

**Comment by alvarolb** [comment]
Hi @dudesky71 can you share the sketch you are using? (without credentials).

Bests.

**Comment by dudesky71** [comment]
<pre>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">DNSServer</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><b><font color="#d35400">WiFiManager</font></b><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">ESP8266WiFi</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">ThingerESP8266</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">DHT</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>

<font color="#5e6d03">#define</font> <font color="#000000">USERNAME</font> <font color="#005c5f">"xxx"</font>
<font color="#5e6d03">#define</font> <font color="#000000">DEVICE_ID</font> <font color="#005c5f">"esp8266"</font>
<font color="#5e6d03">#define</font> <font color="#000000">DEVICE_CREDENTIAL</font> <font color="#005c5f">"xxx"</font>

<font color="#434f54">// Initialize DHT sensor.</font>
<font color="#5e6d03">#define</font> <font color="#000000">DHTPIN</font> <font color="#000000">4</font> &nbsp;&nbsp;&nbsp;&nbsp;<font color="#434f54">// what digital pin we're connected to. Mapped to pin D2 on WeMOS</font>
<font color="#5e6d03">#define</font> <font color="#000000">DHTTYPE</font> <font color="#000000">DHT11</font> &nbsp;&nbsp;<font color="#434f54">// DHT 11</font>
<font color="#5e6d03">#define</font> <font color="#000000">ANALOG_PIN</font> <font color="#000000">A0</font> &nbsp;<font color="#434f54">// ADC pin 0</font>
<font color="#000000">DHT</font> <font color="#000000">dht</font><font color="#000000">(</font><font color="#000000">DHTPIN</font><font color="#434f54">,</font> <font color="#000000">DHTTYPE</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">// Set up Thinger varibles</font>
<font color="#000000">ThingerESP8266</font> <font color="#000000">thing</font><font color="#000000">(</font><font color="#000000">USERNAME</font><font color="#434f54">,</font> <font color="#000000">DEVICE_ID</font><font color="#434f54">,</font> <font color="#000000">DEVICE_CREDENTIAL</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">// Set up constants</font>
<font color="#00979c">float</font> <font color="#000000">temp</font> <font color="#434f54">=</font> <font color="#000000">0</font><font color="#000000">;</font>
<font color="#00979c">int</font> <font color="#000000">hum</font> <font color="#434f54">=</font> <font color="#000000">0</font><font color="#000000">;</font>
<font color="#00979c">int</font> <font color="#000000">adc</font> <font color="#434f54">=</font> <font color="#000000">0</font><font color="#000000">;</font>
<font color="#00979c">unsigned</font> <font color="#00979c">long</font> <font color="#000000">previousMillis</font> <font color="#434f54">=</font> <font color="#000000">0</font><font color="#000000">;</font>
<font color="#00979c">const</font> <font color="#00979c">long</font> <font color="#000000">interval</font> <font color="#434f54">=</font> <font color="#000000">5000</font><font color="#000000">;</font>

<font color="#00979c">void</font> <font color="#5e6d03">setup</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>

<font color="#434f54">// start the serial connection</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">begin</font><font color="#000000">(</font><font color="#000000">115200</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">""</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">//WiFiManager</font>
 &nbsp;<font color="#434f54">//Local intialization. Once its business is done, there is no need to keep it around</font>
 &nbsp;<b><font color="#d35400">WiFiManager</font></b> <font color="#000000">wifiManager</font><font color="#000000">;</font>
 &nbsp;<font color="#434f54">//reset saved settings</font>
 &nbsp;<font color="#434f54">//wifiManager.resetSettings();</font>

 &nbsp;<font color="#434f54">//set custom ip for portal</font>
 &nbsp;<font color="#434f54">//wifiManager.setAPConfig(IPAddress(10,0,1,1), IPAddress(10,0,1,1), IPAddress(255,255,255,0));</font>

 &nbsp;<font color="#434f54">//fetches ssid and pass from eeprom and tries to connect</font>
 &nbsp;<font color="#434f54">//if it does not connect it starts an access point with the specified name</font>
 &nbsp;<font color="#434f54">//here &nbsp;"AutoConnectAP"</font>
 &nbsp;<font color="#434f54">//and goes into a blocking loop awaiting configuration</font>
 &nbsp;<font color="#434f54">//wifiManager.autoConnect("Test-DongleAP");</font>
 &nbsp;<font color="#434f54">//or use this for auto generated name ESP + ChipID</font>
 &nbsp;<font color="#000000">wifiManager</font><font color="#434f54">.</font><font color="#d35400">autoConnect</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>


<font color="#434f54">//if you get here you have connected to the WiFi</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">""</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">"Connected to WiFi Network..."</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><b><font color="#d35400">WiFi</font></b><font color="#434f54">.</font><font color="#d35400">SSID</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#434f54">//Serial.println(WiFi.psk());</font>
 &nbsp;
<font color="#434f54">// Setup Thinger IO feeds</font>
 &nbsp;<font color="#434f54">// more details at </font><u><font color="#434f54">http://docs.thinger.io/arduino/</font></u><font color="#434f54"></font>

 <font color="#434f54">// thing.add_wifi(SSID, SSID_PASSWORD);</font>

 &nbsp;<font color="#434f54">// digital pin input from Thinger control example (i.e. turning on/off a light, a relay, configuring a parameter, etc)</font>
 &nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"led"</font><font color="#000000">]</font> <font color="#434f54">&lt;&lt;</font> <font color="#000000">digitalPin</font><font color="#000000">(</font><font color="#000000">BUILTIN_LED</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#434f54">// resource output to Thinger example (i.e. reading a sensor value)</font>
 &nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"millis"</font><font color="#000000">]</font> <font color="#434f54">&gt;&gt;</font> <font color="#000000">outputValue</font><font color="#000000">(</font><font color="#d35400">millis</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"temp"</font><font color="#000000">]</font> <font color="#434f54">&gt;&gt;</font> <font color="#000000">outputValue</font><font color="#000000">(</font><font color="#000000">temp</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"hum"</font><font color="#000000">]</font> <font color="#434f54">&gt;&gt;</font> <font color="#000000">outputValue</font><font color="#000000">(</font><font color="#000000">hum</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"adc"</font><font color="#000000">]</font> <font color="#434f54">&gt;&gt;</font> <font color="#000000">outputValue</font><font color="#000000">(</font><font color="#000000">adc</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#000000">dht</font><font color="#434f54">.</font><font color="#d35400">begin</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">100</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">connectGoodLED</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">}</font>

<font color="#00979c">void</font> <font color="#5e6d03">loop</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;
 &nbsp;<font color="#00979c">unsigned</font> <font color="#00979c">long</font> <font color="#000000">currentMillis</font> <font color="#434f54">=</font> <font color="#d35400">millis</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#5e6d03">if</font> <font color="#000000">(</font><font color="#000000">currentMillis</font> <font color="#434f54">-</font> <font color="#000000">previousMillis</font> <font color="#434f54">&gt;=</font> <font color="#000000">interval</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">previousMillis</font> <font color="#434f54">=</font> <font color="#000000">currentMillis</font><font color="#000000">;</font>

 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">thing</font><font color="#434f54">.</font><font color="#000000">handle</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">readDHT</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">readADC</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">showValues</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">dataSentLED</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">}</font>
<font color="#000000">}</font>

 &nbsp;<font color="#434f54">//////////////////// FUNCTIONS ////////////////////</font>
 &nbsp;
 &nbsp;<font color="#00979c">void</font> <font color="#000000">readDHT</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;<font color="#434f54">// Read the DHT Sensor</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#005c5f">"Reading Sensor..."</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">""</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">temp</font> <font color="#434f54">=</font> <font color="#000000">dht</font><font color="#434f54">.</font><font color="#d35400">readTemperature</font><font color="#000000">(</font><font color="#00979c">true</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font> <font color="#000000">(</font><font color="#000000">500</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"temp"</font><font color="#000000">]</font> <font color="#434f54">&gt;&gt;</font> <font color="#000000">outputValue</font><font color="#000000">(</font><font color="#000000">temp</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">hum</font> <font color="#434f54">=</font> <font color="#000000">dht</font><font color="#434f54">.</font><font color="#000000">readHumidity</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font> <font color="#000000">(</font><font color="#000000">500</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"hum"</font><font color="#000000">]</font> <font color="#434f54">&gt;&gt;</font> <font color="#000000">outputValue</font><font color="#000000">(</font><font color="#000000">hum</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">}</font>

 &nbsp;<font color="#00979c">void</font> <font color="#000000">readADC</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">{</font>
 <font color="#434f54">// Read ADC input</font>
<font color="#000000">adc</font> <font color="#434f54">=</font> <font color="#d35400">analogRead</font><font color="#000000">(</font><font color="#000000">ANALOG_PIN</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#5e6d03">if</font> <font color="#000000">(</font><font color="#000000">adc</font> <font color="#434f54">&lt;=</font> <font color="#000000">10</font><font color="#000000">)</font><font color="#000000">adc</font> <font color="#434f54">=</font> <font color="#000000">0</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font> <font color="#000000">(</font><font color="#000000">500</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">thing</font><font color="#000000">[</font><font color="#005c5f">"adc"</font><font color="#000000">]</font> <font color="#434f54">&gt;&gt;</font> <font color="#000000">outputValue</font><font color="#000000">(</font><font color="#000000">adc</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">}</font>
 &nbsp;
 &nbsp;<font color="#00979c">void</font> <font color="#000000">connectGoodLED</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
 <font color="#434f54">// Blink the blue LED three times for WiFi connection confirmation</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">pinMode</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">OUTPUT</font><font color="#000000">)</font><font color="#000000">;</font> <font color="#434f54">// set blue led pin to output</font>
 &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED on</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">50</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED off</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">200</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED on</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">50</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED off</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">200</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED on</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">50</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED off</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">""</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;<font color="#000000">}</font>

 &nbsp;&nbsp;<font color="#00979c">void</font> <font color="#000000">showValues</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">{</font>
 <font color="#434f54">// Print values to debug colsole window</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#005c5f">"Wetness: "</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#000000">adc</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">""</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#005c5f">"Temperature: "</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#000000">temp</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">"F "</font><font color="#000000">)</font><font color="#000000">;</font>
 
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#005c5f">"Humidity: "</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#000000">hum</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">"% "</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;<font color="#000000">}</font>

 &nbsp;<font color="#00979c">void</font> <font color="#000000">dataSentLED</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">{</font>
 <font color="#434f54">// Blink the blue LED once for data sent confirmation</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">"Data Sent... "</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">""</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">LOW</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED on</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">delay</font><font color="#000000">(</font><font color="#000000">100</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#d35400">digitalWrite</font><font color="#000000">(</font><font color="#000000">2</font><font color="#434f54">,</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;<font color="#434f54">// sets the LED off</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">}</font>


</pre>

**Comment by dudesky71** [comment]
Keep in mind the same issue occurs even WiFi Manager is not used.

**Comment by alvarolb** [comment]
Hi @dudesky71 looking at the code, there are a lot of optimizations to be done here, and also some problems while using the library.

First of all, the thing.handle() must be done inside the loop, without any delay (as much as possible).
Also I suggest you to avoid the sensor readings inside the loop, and read the values only once required. This way, you can change easily the sampling frequency. Try this code instead: 

```cpp
#include <WiFiManager.h>
#include <ESP8266WiFi.h>
#include <ThingerESP8266.h>
#include <DHT.h>

#define USERNAME "xxx"
#define DEVICE_ID "esp8266"
#define DEVICE_CREDENTIAL "xxx"

// Initialize DHT sensor.
#define DHTPIN 4     // what digital pin we're connected to. Mapped to pin D2 on WeMOS
#define DHTTYPE DHT11   // DHT 11
#define ANALOG_PIN A0  // ADC pin 0
DHT dht(DHTPIN, DHTTYPE);

// Set up Thinger varibles
ThingerESP8266 thing(USERNAME, DEVICE_ID, DEVICE_CREDENTIAL);

// Set up constants
float temp = 0;
int hum = 0;
int adc = 0;
unsigned long previousMillis = 0;
const long interval = 5000;

void setup() {

// start the serial connection
  Serial.begin(115200);
  Serial.println("");

//WiFiManager
  //Local intialization. Once its business is done, there is no need to keep it around
  WiFiManager wifiManager;
  //reset saved settings
  //wifiManager.resetSettings();

  //set custom ip for portal
  //wifiManager.setAPConfig(IPAddress(10,0,1,1), IPAddress(10,0,1,1), IPAddress(255,255,255,0));

  //fetches ssid and pass from eeprom and tries to connect
  //if it does not connect it starts an access point with the specified name
  //here  "AutoConnectAP"
  //and goes into a blocking loop awaiting configuration
  //wifiManager.autoConnect("Test-DongleAP");
  //or use this for auto generated name ESP + ChipID
  wifiManager.autoConnect();


//if you get here you have connected to the WiFi
  Serial.println("");
  Serial.println("Connected to WiFi Network...");
  Serial.println(WiFi.SSID());
  //Serial.println(WiFi.psk());
  
// Setup Thinger IO feeds
  // more details at http://docs.thinger.io/arduino/

 // thing.add_wifi(SSID, SSID_PASSWORD);

  // digital pin input from Thinger control example (i.e. turning on/off a light, a relay, configuring a parameter, etc)
  thing["led"] << digitalPin(BUILTIN_LED);

  // resource output to Thinger example (i.e. reading a sensor value)
  thing["millis"] >> outputValue(millis());
  thing["temp"] >> outputValue(dht.readTemperature(true));
  thing["hum"] >> outputValue(dht.readHumidity());
  thing["adc"] >> analogPin(ANALOG_PIN);

  dht.begin();
  delay(100);
  connectGoodLED();
}

void loop() {
  thing.handle();
}
  
void connectGoodLED() {
 // Blink the blue LED three times for WiFi connection confirmation
    pinMode(2, OUTPUT); // set blue led pin to output
  digitalWrite(2, LOW);   // sets the LED on
    delay(50);
  digitalWrite(2, HIGH);   // sets the LED off
    delay(200);
  digitalWrite(2, LOW);   // sets the LED on
    delay(50);
  digitalWrite(2, HIGH);   // sets the LED off
    delay(200);
  digitalWrite(2, LOW);   // sets the LED on
    delay(50);
  digitalWrite(2, HIGH);   // sets the LED off
  Serial.println("");
 }
```

I recommend also to take a look to the example ESP8266WebConfig in the thinger.io libraries, as it uses WebConfig for setting both WIFI and username, device, and credentials.

Hope it helps!

**Comment by dudesky71** [comment]
I would also like to add that I've been testing for a few weeks and yesterday I stumbled across something. It appears that when connecting to my hotspot on my iPhone that it seems more stable than when connecting on my home network. I use a pfSense router with running 2.3.2-p1 firmware. Could my firewall slowly block the ports? Should I port forward port 25200 and port 25202 to the IP address of the module?

**Comment by alvarolb** [comment]
Try the above code, you should see a smooth interaction in the platform and your device. The API explorer will load quite fast, and you could see how changing sampling intervals over sensors will take effect on the charts. At this moment you were tied to the 5s delay that were stopping everything.

**Comment by dudesky71** [comment]
@alvarolb I don't have to have the 5 seconds in there. I just added it so I wasnt hitting the Thinger server constantly. Could my code be timing out? Is it ok to delete my delays?

**Comment by alvarolb** [comment]
Don't worry about the thing.handle() call. This will not send any data to thinger if not required by the server. This handle is mainly for reading sensor commands. Your code is still bad if you delete the delays, as, this code `thing["hum"] >> outputValue(hum);` you use for sending data, will not actually send data, instead will redefine the resource, and will cause your device to crash eventually.
Just test the code i provided, and you should see a great difference.

**Comment by alvarolb** [comment]
Notice that you were "sending" all data every 5 seconds, but thinger.io, lets you send any single value at a dynamic interval that can be configured from the console. So the handle is there to recognize when it is required to stream a value or another, change the sampling frequency, and so on.

**Comment by dudesky71** [comment]
@alvarolb Great catch! I'm a dork :) thank you for the code example :) I'll try this and see how it goes. I like the web config example but for my project, I don't want to have to enter in the thinger credentials. I like it to be set constant.

**Comment by alvarolb** [comment]
ok! let me now how it goes ;)

**Comment by dudesky71** [comment]
@alvarolb So.... with my original code, was I causing the module to eventually run out of RAM by redefining the resource? Also, Should I not add anything else into the main loop?

**Comment by alvarolb** [comment]
Yes, you were probably running your resource out of RAM by creating a lambda function once and again. The loop for your actual use case can be keep as is, with the thing.handle call.

**Comment by dudesky71** [comment]
@alvarolb When i run your sketch by connecting directly to my iPhone hotspot, it seems to run fine. If I connect to my work WiFi, I stop getting reads from millis counter within a few minutes inside the thinger dashboard. I then get the thumbs down icons in my dashboard and it never recovers unless i reboot the module and then it happens again... I would imagine on my home network I will see the same thing happen. It will run for 8-10 hours then hang. I'll be running the new test at home this weekend.

**Comment by alvarolb** [comment]
Hi @dudesky71, did you have the latests Arduino libraries?

**Comment by dudesky71** [comment]
I would also like to send an email via endpoint in my sketch. I need to look at the ADC value and if above a certain number, send the email. Before I had the if statement in the function that was called in the main loop. How would you suggest adding this to not affect the timing?

**Comment by alvarolb** [comment]
You can just introduce code in the loop, reading ADCs, or sensor values it not a problem at all. Check the example in the community that alerts when a plant is out of water:

https://community.thinger.io/t/internet-of-things-moisture-sensor-with-esp8266/24

**Comment by dudesky71** [comment]
@alvarolb Yes. I have all the latest libraries and IDE.

**Comment by dudesky71** [comment]
@alvarolb So far your code is running well :) I've been running tests all weekend. I've added in my ADC sensor read and flashing the LED in the main loop. So far so good. Each test ran for 24 hours with no issues. I'm now letting it run for 5 days to see how it goes. Thank you for the heads up on the Lamda function. I didn't realize I was even causing this issue with my original code.

**Comment by alvarolb** [comment]
Great! Good to know it is working right now! Thanks for testing @dudesky71 !! Let me know how your long running test work to close the issue! :)

**Comment by alvarolb** [comment]
Hi @dudesky71 ! Any results on your long running test?

**Comment by dudesky71** [comment]
@alvarolb Hello and thanks for checking in. I kept tweaking my code for more data reporting so I've reset it a few times. The longest run I got out of it was 4.5 days and I had a power outage at home :( It's back up and running now again so I will let it run and report back as to how long I get out of it :) So far so good :)
